package pe.interbank.exchange.domain;

import lombok.Getter;

@Getter
public enum Currency {
    AED("AED", "د.إ", "Dirham de los Emiratos Árabes Unidos", "Emiratos Árabes Unidos", "https://flagcdn.com/ae.svg"),
    AFN("AFN", "؋", "Afgani afgano", "Afganistán", "https://flagcdn.com/af.svg"),
    ALL("ALL", "L", "Lek albanés", "Albania", "https://flagcdn.com/al.svg"),
    AMD("AMD", "֏", "Dram armenio", "Armenia", "https://flagcdn.com/am.svg"),
    ANG("ANG", "ƒ", "Florín de las Antillas Neerlandesas", "Antillas Neerlandesas", "https://flagcdn.com/an.svg"),
    AOA("AOA", "Kz", "Kwanza angoleño", "Angola", "https://flagcdn.com/ao.svg"),
    ARS("ARS", "$", "Peso argentino", "Argentina", "https://flagcdn.com/ar.svg"),
    AUD("AUD", "$", "Dólar australiano", "Australia", "https://flagcdn.com/au.svg"),
    AWG("AWG", "ƒ", "Florín arubeño", "Aruba", "https://flagcdn.com/aw.svg"),
    AZN("AZN", "₼", "Manat azerbaiyano", "Azerbaiyán", "https://flagcdn.com/az.svg"),
    BAM("BAM", "KM", "Marco convertible de Bosnia-Herzegovina", "Bosnia y Herzegovina", "https://flagcdn.com/ba.svg"),
    BBD("BBD", "$", "Dólar de Barbados", "Barbados", "https://flagcdn.com/bb.svg"),
    BDT("BDT", "৳", "Taka bangladesí", "Bangladesh", "https://flagcdn.com/bd.svg"),
    BGN("BGN", "лв", "Lev búlgaro", "Bulgaria", "https://flagcdn.com/bg.svg"),
    BHD("BHD", "ب.د", "Dinar bahreiní", "Bahréin", "https://flagcdn.com/bh.svg"),
    BIF("BIF", "Fr", "Franco burundés", "Burundi", "https://flagcdn.com/bi.svg"),
    BMD("BMD", "$", "Dólar bermudeño", "Bermudas", "https://flagcdn.com/bm.svg"),
    BND("BND", "$", "Dólar de Brunéi", "Brunéi", "https://flagcdn.com/bn.svg"),
    BOB("BOB", "Bs.", "Boliviano boliviano", "Bolivia", "https://flagcdn.com/bo.svg"),
    BRL("BRL", "R$", "Real brasileño", "Brasil", "https://flagcdn.com/br.svg"),
    BSD("BSD", "$", "Dólar bahameño", "Bahamas", "https://flagcdn.com/bs.svg"),
    BTN("BTN", "Nu.", "Ngultrum butanés", "Bután", "https://flagcdn.com/bt.svg"),
    BWP("BWP", "P", "Pula botsuano", "Botsuana", "https://flagcdn.com/bw.svg"),
    BYN("BYN", "Br", "Rublo bielorruso", "Bielorrusia", "https://flagcdn.com/by.svg"),
    BZD("BZD", "BZ$", "Dólar beliceño", "Belice", "https://flagcdn.com/bz.svg"),
    CAD("CAD", "$", "Dólar canadiense", "Canadá", "https://flagcdn.com/ca.svg"),
    CDF("CDF", "FC", "Franco congoleño", "República Democrática del Congo", "https://flagcdn.com/cd.svg"),
    CHF("CHF", "Fr", "Franco suizo", "Suiza", "https://flagcdn.com/ch.svg"),
    CLP("CLP", "$", "Peso chileno", "Chile", "https://flagcdn.com/cl.svg"),
    CNY("CNY", "¥", "Yuan chino", "China", "https://flagcdn.com/cn.svg"),
    COP("COP", "$", "Peso colombiano", "Colombia", "https://flagcdn.com/co.svg"),
    CRC("CRC", "₡", "Colón costarricense", "Costa Rica", "https://flagcdn.com/cr.svg"),
    CUP("CUP", "$", "Peso cubano", "Cuba", "https://flagcdn.com/cu.svg"),
    CVE("CVE", "$", "Escudo caboverdiano", "Cabo Verde", "https://flagcdn.com/cv.svg"),
    CZK("CZK", "Kč", "Corona checa", "República Checa", "https://flagcdn.com/cz.svg"),
    DJF("DJF", "Fdj", "Franco yibutiano", "Yibuti", "https://flagcdn.com/dj.svg"),
    DKK("DKK", "kr", "Corona danesa", "Dinamarca", "https://flagcdn.com/dk.svg"),
    DOP("DOP", "RD$", "Peso dominicano", "República Dominicana", "https://flagcdn.com/do.svg"),
    DZD("DZD", "د.ج", "Dinar argelino", "Argelia", "https://flagcdn.com/dz.svg"),
    EGP("EGP", "ج.م", "Libra egipcia", "Egipto", "https://flagcdn.com/eg.svg"),
    ERN("ERN", "Nfk", "Nakfa eritreo", "Eritrea", "https://flagcdn.com/er.svg"),
    ETB("ETB", "Br", "Birr etíope", "Etiopía", "https://flagcdn.com/et.svg"),
    EUR("EUR", "€", "Euro", "Eurozona", "https://flagcdn.com/eu.svg"),
    FJD("FJD", "FJ$", "Dólar fiyiano", "Fiyi", "https://flagcdn.com/fj.svg"),
    FKP("FKP", "£", "Libra de las Islas Malvinas", "Islas Malvinas", "https://flagcdn.com/fk.svg"),
    FOK("FOK", "kr", "Corona faroesa", "Islas Feroe", "https://flagcdn.com/fo.svg"),
    GBP("GBP", "£", "Libra esterlina británica", "Reino Unido", "https://flagcdn.com/gb.svg"),
    GEL("GEL", "₾", "Lari georgiano", "Georgia", "https://flagcdn.com/ge.svg"),
    GGP("GGP", "£", "Libra de Guernsey", "Guernsey", "https://flagcdn.com/gg.svg"),
    GHS("GHS", "GH₵", "Cedi ghanés", "Ghana", "https://flagcdn.com/gh.svg"),
    GIP("GIP", "£", "Libra de Gibraltar", "Gibraltar", "https://flagcdn.com/gi.svg"),
    GMD("GMD", "D", "Dalasi gambiano", "Gambia", "https://flagcdn.com/gm.svg"),
    GNF("GNF", "Fr", "Franco guineano", "Guinea", "https://flagcdn.com/gn.svg"),
    GTQ("GTQ", "Q", "Quetzal guatemalteco", "Guatemala", "https://flagcdn.com/gt.svg"),
    GYD("GYD", "GY$", "Dólar guyanés", "Guyana", "https://flagcdn.com/gy.svg"),
    HKD("HKD", "HK$", "Dólar de Hong Kong", "Hong Kong", "https://flagcdn.com/hk.svg"),
    HNL("HNL", "L", "Lempira hondureño", "Honduras", "https://flagcdn.com/hn.svg"),
    HRK("HRK", "kn", "Kuna croata", "Croacia", "https://flagcdn.com/hr.svg"),
    HTG("HTG", "G", "Gourde haitiano", "Haití", "https://flagcdn.com/ht.svg"),
    HUF("HUF", "Ft", "Forinto húngaro", "Hungría", "https://flagcdn.com/hu.svg"),
    IDR("IDR", "Rp", "Rupia indonesia", "Indonesia", "https://flagcdn.com/id.svg"),
    ILS("ILS", "₪", "Nuevo shéquel israelí", "Israel", "https://flagcdn.com/il.svg"),
    IMP("IMP", "£", "Libra de la Isla de Man", "Isla de Man", "https://flagcdn.com/im.svg"),
    INR("INR", "₹", "Rupia india", "India", "https://flagcdn.com/in.svg"),
    IQD("IQD", "ع.د", "Dinar iraquí", "Irak", "https://flagcdn.com/iq.svg"),
    IRR("IRR", "﷼", "Rial iraní", "Irán", "https://flagcdn.com/ir.svg"),
    ISK("ISK", "kr", "Corona islandesa", "Islandia", "https://flagcdn.com/is.svg"),
    JEP("JEP", "£", "Libra de Jersey", "Jersey", "https://flagcdn.com/je.svg"),
    JMD("JMD", "J$", "Dólar jamaicano", "Jamaica", "https://flagcdn.com/jm.svg"),
    JOD("JOD", "د.ا", "Dinar jordano", "Jordania", "https://flagcdn.com/jo.svg"),
    JPY("JPY", "¥", "Yen japonés", "Japón", "https://flagcdn.com/jp.svg"),
    KES("KES", "KSh", "Chelín keniano", "Kenia", "https://flagcdn.com/ke.svg"),
    KGS("KGS", "с", "Som kirguís", "Kirguistán", "https://flagcdn.com/kg.svg"),
    KHR("KHR", "៛", "Riel camboyano", "Camboya", "https://flagcdn.com/kh.svg"),
    KID("KID", "$", "Dólar de Kiribati", "Kiribati", "https://flagcdn.com/ki.svg"),
    KMF("KMF", "Fr", "Franco comorense", "Comoras", "https://flagcdn.com/km.svg"),
    KRW("KRW", "₩", "Won surcoreano", "Corea del Sur", "https://flagcdn.com/kr.svg"),
    KWD("KWD", "د.ك", "Dinar kuwaití", "Kuwait", "https://flagcdn.com/kw.svg"),
    KYD("KYD", "$", "Dólar de las Islas Caimán", "Islas Caimán", "https://flagcdn.com/ky.svg"),
    KZT("KZT", "₸", "Tenge kazajo", "Kazajistán", "https://flagcdn.com/kz.svg"),
    LAK("LAK", "₭", "Kip laosiano", "Laos", "https://flagcdn.com/la.svg"),
    LBP("LBP", "ل.ل", "Libra libanesa", "Líbano", "https://flagcdn.com/lb.svg"),
    LKR("LKR", "රු", "Rupia de Sri Lanka", "Sri Lanka", "https://flagcdn.com/lk.svg"),
    LRD("LRD", "$", "Dólar liberiano", "Liberia", "https://flagcdn.com/lr.svg"),
    LSL("LSL", "L", "Loti lesothense", "Lesoto", "https://flagcdn.com/ls.svg"),
    LYD("LYD", "ل.د", "Dinar libio", "Libia", "https://flagcdn.com/ly.svg"),
    MAD("MAD", "د.م.", "Dirham marroquí", "Marruecos", "https://flagcdn.com/ma.svg"),
    MDL("MDL", "L", "Leu moldavo", "Moldavia", "https://flagcdn.com/md.svg"),
    MGA("MGA", "Ar", "Ariary malgache", "Madagascar", "https://flagcdn.com/mg.svg"),
    MKD("MKD", "ден", "Denar macedonio", "Macedonia del Norte", "https://flagcdn.com/mk.svg"),
    MMK("MMK", "Ks", "Kyat birmano", "Myanmar", "https://flagcdn.com/mm.svg"),
    MNT("MNT", "₮", "Tugrik mongol", "Mongolia", "https://flagcdn.com/mn.svg"),
    MOP("MOP", "MOP$", "Pataca de Macao", "Macao", "https://flagcdn.com/mo.svg"),
    MRU("MRU", "UM", "Ugía mauritana", "Mauritania", "https://flagcdn.com/mr.svg"),
    MUR("MUR", "Rs", "Rupia mauriciana", "Mauricio", "https://flagcdn.com/mu.svg"),
    MVR("MVR", "Rf", "Rupia de Maldivas", "Maldivas", "https://flagcdn.com/mv.svg"),
    MWK("MWK", "MK", "Kwacha malauí", "Malaui", "https://flagcdn.com/mw.svg"),
    MXN("MXN", "$", "Peso mexicano", "México", "https://flagcdn.com/mx.svg"),
    MYR("MYR", "RM", "Ringgit malayo", "Malasia", "https://flagcdn.com/my.svg"),
    MZN("MZN", "MT", "Metical mozambiqueño", "Mozambique", "https://flagcdn.com/mz.svg"),
    NAD("NAD", "N$", "Dólar namibio", "Namibia", "https://flagcdn.com/na.svg"),
    NGN("NGN", "₦", "Naira nigeriana", "Nigeria", "https://flagcdn.com/ng.svg"),
    NIO("NIO", "C$", "Córdoba nicaragüense", "Nicaragua", "https://flagcdn.com/ni.svg"),
    NOK("NOK", "kr", "Corona noruega", "Noruega", "https://flagcdn.com/no.svg"),
    NPR("NPR", "रू", "Rupia nepalí", "Nepal", "https://flagcdn.com/np.svg"),
    NZD("NZD", "$", "Dólar neozelandés", "Nueva Zelanda", "https://flagcdn.com/nz.svg"),
    OMR("OMR", "ر.ع.", "Rial omaní", "Omán", "https://flagcdn.com/om.svg"),
    PAB("PAB", "B/.", "Balboa panameño", "Panamá", "https://flagcdn.com/pa.svg"),
    PEN("PEN", "S/.", "Sol peruano", "Perú", "https://flagcdn.com/pe.svg"),
    PGK("PGK", "K", "Kina papú", "Papúa Nueva Guinea", "https://flagcdn.com/pg.svg"),
    PHP("PHP", "₱", "Peso filipino", "Filipinas", "https://flagcdn.com/ph.svg"),
    PKR("PKR", "₨", "Rupia pakistaní", "Pakistán", "https://flagcdn.com/pk.svg"),
    PLN("PLN", "zł", "Złoty polaco", "Polonia", "https://flagcdn.com/pl.svg"),
    PYG("PYG", "₲", "Guaraní paraguayo", "Paraguay", "https://flagcdn.com/py.svg"),
    QAR("QAR", "ر.ق", "Rial qatarí", "Qatar", "https://flagcdn.com/qa.svg"),
    RON("RON", "lei", "Leu rumano", "Rumanía", "https://flagcdn.com/ro.svg"),
    RSD("RSD", "din", "Dinar serbio", "Serbia", "https://flagcdn.com/rs.svg"),
    RUB("RUB", "₽", "Rublo ruso", "Rusia", "https://flagcdn.com/ru.svg"),
    RWF("RWF", "Fr", "Franco ruandés", "Ruanda", "https://flagcdn.com/rw.svg"),
    SAR("SAR", "ر.س", "Riyal saudí", "Arabia Saudita", "https://flagcdn.com/sa.svg"),
    SBD("SBD", "SI$", "Dólar de las Islas Salomón", "Islas Salomón", "https://flagcdn.com/sb.svg"),
    SCR("SCR", "₨", "Rupia seychellense", "Seychelles", "https://flagcdn.com/sc.svg"),
    SDG("SDG", "ج.س.", "Libra sudanesa", "Sudán", "https://flagcdn.com/sd.svg"),
    SEK("SEK", "kr", "Corona sueca", "Suecia", "https://flagcdn.com/se.svg"),
    SGD("SGD", "$", "Dólar de Singapur", "Singapur", "https://flagcdn.com/sg.svg"),
    SHP("SHP", "£", "Libra de Santa Elena", "Santa Elena", "https://flagcdn.com/sh.svg"),
    SLL("SLL", "Le", "Leone sierraleonés", "Sierra Leona", "https://flagcdn.com/sl.svg"),
    SOS("SOS", "Sh", "Chelín somalí", "Somalia", "https://flagcdn.com/so.svg"),
    SRD("SRD", "SR$", "Dólar surinamés", "Surinam", "https://flagcdn.com/sr.svg"),
    SSP("SSP", "£", "Libra sursudanesa", "Sudán del Sur", "https://flagcdn.com/ss.svg"),
    STN("STN", "Db", "Dobra santotomense", "Santo Tomé y Príncipe", "https://flagcdn.com/st.svg"),
    SYP("SYP", "£", "Libra siria", "Siria", "https://flagcdn.com/sy.svg"),
    SZL("SZL", "L", "Lilangeni suazi", "Esuatini", "https://flagcdn.com/sz.svg"),
    THB("THB", "฿", "Baht tailandés", "Tailandia", "https://flagcdn.com/th.svg"),
    TJS("TJS", "ЅМ", "Somoni tayiko", "Tayikistán", "https://flagcdn.com/tj.svg"),
    TMT("TMT", "T", "Manat turcomano", "Turkmenistán", "https://flagcdn.com/tm.svg"),
    TND("TND", "د.ت", "Dinar tunecino", "Túnez", "https://flagcdn.com/tn.svg"),
    TOP("TOP", "T$", "Pa'anga tongano", "Tonga", "https://flagcdn.com/to.svg"),
    TRY("TRY", "₺", "Lira turca", "Turquía", "https://flagcdn.com/tr.svg"),
    TTD("TTD", "TT$", "Dólar de Trinidad y Tobago", "Trinidad y Tobago", "https://flagcdn.com/tt.svg"),
    TWD("TWD", "NT$", "Nuevo dólar taiwanés", "Taiwán", "https://flagcdn.com/tw.svg"),
    TZS("TZS", "Sh", "Chelín tanzano", "Tanzania", "https://flagcdn.com/tz.svg"),
    UAH("UAH", "₴", "Grivna ucraniana", "Ucrania", "https://flagcdn.com/ua.svg"),
    UGX("UGX", "Sh", "Chelín ugandés", "Uganda", "https://flagcdn.com/ug.svg"),
    USD("USD", "$", "Dólar estadounidense", "Estados Unidos", "https://flagcdn.com/us.svg"),
    UYU("UYU", "$", "Peso uruguayo", "Uruguay", "https://flagcdn.com/uy.svg"),
    UZS("UZS", "лв", "Som uzbeko", "Uzbekistán", "https://flagcdn.com/uz.svg"),
    VES("VES", "Bs.", "Bolívar venezolano", "Venezuela", "https://flagcdn.com/ve.svg"),
    VND("VND", "₫", "Dong vietnamita", "Vietnam", "https://flagcdn.com/vn.svg"),
    VUV("VUV", "VT", "Vatu vanuatuense", "Vanuatu", "https://flagcdn.com/vu.svg"),
    WST("WST", "WS$", "Tala samoano", "Samoa", "https://flagcdn.com/ws.svg"),
    XAF("XAF", "Fr", "Franco CFA de África Central", "CFA", "https://flagcdn.com/xa.svg"),
    XCD("XCD", "$", "Dólar del Caribe Oriental", "Organización de Estados del Caribe Oriental", "https://flagcdn.com/xb.svg"),
    XOF("XOF", "Fr", "Franco CFA de África Occidental", "Francia", "https://flagcdn.com/xb.svg"),
    XPF("XPF", "Fr", "Franco CFP", "CFA", "https://flagcdn.com/xc.svg"),
    YER("YER", "﷼", "Rial yemení", "Yemen", "https://flagcdn.com/ye.svg"),
    ZAR("ZAR", "R", "Rand sudafricano", "Sudáfrica", "https://flagcdn.com/za.svg"),
    ZMW("ZMW", "ZK", "Kwacha zambiano", "Zambia", "https://flagcdn.com/zm.svg"),
    ZWL("ZWL", "$", "Dólar zimbabuense", "Zimbabue", "https://flagcdn.com/zw.svg");

    private final String code;
    private final String symbol;
    private final String name;
    private final String country;
    private final String flagUrl;

    Currency(String code, String symbol, String name, String country, String flagUrl) {
        this.code = code;
        this.symbol = symbol;
        this.name = name;
        this.country = country;
        this.flagUrl = flagUrl;
    }
}
